### ISSUE TITLE
nelze prehrat film

### ISSUE THREAD

**Issue by joazif** [kodi-czsk/script.module.stream.resolver#47]
Ahoj,
u doplnku [plugin.video.sledujufilmy.cz](https://github.com/kodi-czsk/plugin.video.sledujufilmy.cz/issues/8) nelze prehrat video jelikoz to pise :  Video je na serveru, ktery neni podporovan
Dle @Lubo je problem v tomto stream resolveru. 
Je tedy mozne to opravit ?

kodi 16.1 Git:20160424-c327c53

Diky 

```
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6e6f63692d73656c69656d2f31343931312f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6a697a64612d762d626f7572692f31343838342f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f62616e6a6f2d6861636b6574742f31343838352f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f626f6a6f766e6963692d7a652d73616f6c696e752f31343839312f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f7265746f726e61646f2f31343839342f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f76652d7374696e752d6d65736963652f31343839332f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f7472696365742d6c65742d7a69766f74612f31343839362f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f636c61737369632f31343839382f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6d6172692d69796167692f31343839392f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f7365796368656c792d7065726c612d696e6469636b65686f2d6f6365616e752f31343930322f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6e6967656c2d6d617276656e2d612d706f6c61726e692d6d65647665642f31343930312f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6c6164792d612d7472616d702d322d7472616d706f76652d646f62726f6472757a737476612f31343930362f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f72696e672d6f662d666972652f31343930372f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f68796472612d7374726174656e792d6f7374726f762f31343930382f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.sledujufilmy.cz/?play=687474703a2f2f736c6564756a7566696c6d792e637a2f66696c6d2f6d6574682d6b6973732d6f662d64656174682f31343931302f&cp=736c6564756a7566696c6d792e637a&
17:46:12 T:3468  NOTICE: ["Initializing provider sledujufilmy.cz with settings {'downloads': '', 'quality': '0'}"]
17:46:14 T:3468  NOTICE: [u'Found resolvable mailto:tvujkamos@email.cz?subject=Koukni na tenle film&body=Ahoj, koukni na film T\u0159icet let \u017eivota. Najde\u0161 ho na adrese http://sledujufilmy.cz/film/tricet-let-zivota/14896/']
17:46:14 T:3468  NOTICE: [u'Found resolvable http://exashare.com/embed-n4y62qpyyfhj-660x340.html']
17:46:14 T:3468  NOTICE: [u'Resolving mailto:tvujkamos@email.cz?subject=Koukni na tenle film&body=Ahoj, koukni na film T\u0159icet let \u017eivota. Najde\u0161 ho na adrese http://sledujufilmy.cz/film/tricet-let-zivota/14896/']
17:46:14 T:3468  NOTICE: [u'No resolver found for mailto:tvujkamos@email.cz?subject=Koukni na tenle film&body=Ahoj, koukni na film T\u0159icet let \u017eivota. Najde\u0161 ho na adrese http://sledujufilmy.cz/film/tricet-let-zivota/14896/']
17:46:14 T:3468  NOTICE: [u'Resolving http://exashare.com/embed-n4y62qpyyfhj-660x340.html']
17:46:14 T:3468  NOTICE: ["Using resolver 'exashare'"]
17:46:14 T:3468   ERROR: Traceback (most recent call last):
17:46:14 T:3468   ERROR:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\resolver.py", line 68, in resolve
17:46:14 T:3468   ERROR:     value = resolver.resolve(url)
17:46:14 T:3468   ERROR:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\server\exashareresolver.py", line 41, in resolve
17:46:14 T:3468   ERROR:     data = demjson.decode(data)
17:46:14 T:3468   ERROR:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.demjson\lib\demjson\demjson.py", line 5701, in decode
17:46:14 T:3468   ERROR:     return_stats=(return_stats or write_stats) )
17:46:14 T:3468   ERROR:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.demjson\lib\demjson\demjson.py", line 4917, in decode
17:46:14 T:3468   ERROR:     raise errors[0]
17:46:14 T:3468   ERROR: JSONDecodeError: Can not decode value starting with character u':'
17:46:14 T:3468  NOTICE: [u'There was an error resolving http://exashare.com/embed-n4y62qpyyfhj-660x340.html'] 
```

**Comment by jose1711** [comment]
opravit to mozne je. problem je, ze stranka exashare (ale i mnohych inych resolverov) sa menia prilis rychlo na to, aby sa to zvladalo kontinualne updatovat.
