### ISSUE TITLE
chyba modul requests

### ISSUE THREAD

**Issue by bbaronSVK** [kodi-czsk/script.module.stream.resolver#63]
po update na 1.6.53 hlasi chybu:
`00:13:21.239 T:33912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "C:\Users\******\AppData\Roaming\Kodi\addons\plugin.video.stream-cinema\default.py", line 25, in <module>
                                                from resources.lib.scinema import StreamCinemaContentProvider
                                              File "C:\Users\******\AppData\Roaming\Kodi\addons\plugin.video.stream-cinema\resources\lib\scinema.py", line 23, in <module>
                                                import resolver
                                              File "C:\Users\******\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\resolver.py", line 37, in <module>
                                                exec 'import %s' % module
                                              File "<string>", line 1, in <module>
                                              File "C:\Users\******\AppData\Roaming\Kodi\addons\script.module.stream.resolver\lib\server\dailymotionresolver.py", line 24, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--`

**Comment by jose1711** [comment]
prosim vyskusaj s https://github.com/kodi-czsk/script.module.stream.resolver/pull/65

**Comment by bbaronSVK** [comment]
Funguje

**Comment by bbaronSVK** [comment]
dik
